datasets:
  telco_churn:
    column_mapping:
      categorical_features:
        - SeniorCitizen
        - Partner
        - Dependents
        - PhoneService
        - MultipleLines
        - OnlineSecurity
        - OnlineBackup
        - DeviceProtection
        - TechSupport
        - StreamingTV
        - StreamingMovies
        - PaperlessBilling
        - gender_Female
        - gender_Male
        - Has_InternetService
        - Fiber_optic
        - DSL
        - PaymentMethod_Bank transfer (automatic)
        - PaymentMethod_Credit card (automatic)
        - PaymentMethod_Electronic check
        - PaymentMethod_Mailed check
        - Contract_Month-to-month
        - Contract_One year
        - Contract_Two year
      numerical_features:
        - MonthlyCharges
        - TotalCharges
        - tenure
      target: Churn
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - classification_performance
      - cat_target_drift
service:
  calculation_period_sec: 1
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
